### ISSUE TITLE
[Admin] Archive debates separating them from active ones

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-bcnencomu#1]
**Is your feature request related to a problem? Please describe.**
In any debate component, you (admin or user) can create as many debates as they want. If the component has a lot of debates, is difficult for the admin navigate through the "actives debates".

**Describe the solution you'd like**
As an admin, I want to see only the actives debates (those debates which are not archived) in the management debate' layout. When an admin close a debate, it will be possible to archive this debate. This enchantment only affects the AI and not the UI. The aim is gaining capabilities in order to have a better navigation experience for admins. 

**Describe alternatives you've considered**
We haven't found any alternatives. Feel free to comment yours! 

**Additional context**
- [x] Add the possibility to archive a debate in the AI when the administrator close the debate
![mockup_closedebat_arxivat](https://user-images.githubusercontent.com/40388743/99250090-6f2e7900-280b-11eb-8fa3-bd7275affc21.png)
- [x] Add a new button "Archiving debates" in the debate layout 
![mockup_managedebate_carpetaarxivat](https://user-images.githubusercontent.com/40388743/99250114-76558700-280b-11eb-9d88-e1b762e855de.png)
- [x] Make a new debate layout for "Archiving debates" 
![mockup_carpetaarxivats](https://user-images.githubusercontent.com/40388743/99250135-7c4b6800-280b-11eb-931e-97d5516b31de.png)

I'm not sure about the correct words (archive/trash, current/active), hope you find a suitable ones! 

**Does this issue could impact on users private data?**
No

**Decidim or custom? If Decidim, attach proposal on meta.decidim**
https://meta.decidim.org/processes/roadmap/f/122/proposals/15687

**Comment by verarojman** [comment]
- Will be closed by https://github.com/decidim/decidim/pull/6940/
