### ISSUE TITLE
Add start and end date in the survey component to enabling an automatic open/close answers

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-bcnencomu#2]
**Is your feature request related to a problem? Please describe.**
Managing a survey, is not possible so set up start date and end date right now. This enhancement in survey component, will enable an automatic open/close answers matching the dates defined

**Describe the solution you'd like**

1. As an admin, I can set a start date (and hour)
2. As an admin, I can set a end date (and hour)
3. As a user, I can answer the survey when start date starts
4. As a user, I can't answer the survey when end date ends

**Describe alternatives you've considered**
We are open :)

**Additional context**
Survey participation (answer questions) will not follow the steps of participatory process (if you define stard-end date you don't need to follow the steps)

**Does this issue could impact on users private data?**
No

**Decidim or custom? If Decidim, attach proposal on meta.decidim**
https://meta.decidim.org/processes/roadmap/f/122/proposals/15690?order=recent&page=3

**Comment by verarojman** [comment]
Waiting for https://github.com/decidim/decidim/pull/6948 to be merged

**Comment by paarals** [comment]
necessites revisió de product o de master @verarojman ?

**Comment by verarojman** [comment]
Necessito de master, estic esperant merge d'un mini-PR per afegir un tipus de dades a les opcions.
