### ISSUE TITLE
Habilitar OAUTH registrats Bcn en Comú a Fearless Cities

### ISSUE THREAD

**Issue by paarals** [Platoniq/decidim-bcnencomu#42]
En el tenant https://network.fearlesscities.com no hi haurà habilitat cap formulari de registre. 
Per accedir, es farà a través de dos formes:

- [ ] Log in Decidim. Es convidarà com a usuaris privats als registrats per la conferència.
- [ ] Connexió registrats Bcn en Comú. Si tens un usuari a Bcn en Comú, podràs entrar a la instància de Fearless.

En aquest cas, s'hauria de desenvolupar la segona opció. La primera, es pot fer a través del system, deshabilitant la opció del formulari del registre, i només habilitant accedir amb comptes ja creats. 

![imatge](https://user-images.githubusercontent.com/40388743/122250958-664d7500-ceca-11eb-8db8-87c658089bd6.png)

**Comment by microstudi** [comment]
DONE
![image](https://user-images.githubusercontent.com/1401520/122370770-a3b01200-cf5f-11eb-9ece-1ced39209099.png)
