### ISSUE TITLE
Possibility to set an undefined time in the end date for a debate

### ISSUE THREAD

**Issue by verarojman** [Platoniq/decidim-bcnencomu#5]
**PR to decidim/decidim:**
https://github.com/decidim/decidim/pull/6959

**Related to:**
https://meta.decidim.org/processes/roadmap/f/122/proposals/15688

- [x] Admin UX
- [x] Public debate visualization
- [x] Specs

**Data de finalització de debat indefinit**

A vegades, pot ser que un debat sigui indefinit durant un llarg transcurs de temps o que són permanentes. Per poder-ho anunciar correctament a l’usuari, l’administrador podà definir la opció “Indefinit” en el temps de finalització. 

![image](https://user-images.githubusercontent.com/8806781/100729386-ff9eb900-33c8-11eb-872a-bdcd0105bb7e.png)

**Comment by paarals** [comment]
Per fer això, cal:
- [ ] Afegir la opció de fer un debat obert (temps indefinit) només afecta al backend -> Això genera modificar el layout de la targeta de debat al frontend. Si l'admin selecciona la opció temps indefinit, no es mostra l'inici i finalització del debat. Només es mostra si l'adminsitrador escull la opció "debat amb franja de temps"

![imatge](https://user-images.githubusercontent.com/40388743/100605265-fa2d6a00-3307-11eb-8f80-f57c984bd0f2.png)
![imatge](https://user-images.githubusercontent.com/40388743/100605385-25b05480-3308-11eb-96ed-93f861676fe4.png)
