### ISSUE TITLE
Adjust video size to debate card

### ISSUE THREAD

**Issue by verarojman** [Platoniq/decidim-bcnencomu#6]
**Ajustar la mida del vídeo a la targeta de debat**
Per defecte l’embed puja la imatge de pantalla del vídeo a unes mides determinades. Valdria la pena poder fer-lo més gran o petit segons les necessitats del tipus de debat que s'ha obert.

**Comment by verarojman** [comment]
@paarals could you describe this issue a bit more? I don't know what video it refers to.

**Comment by paarals** [comment]
@verarojman ja no passa, pel que veig. el tema és que si posaven un video embed o un video amb l'editor de descripció de debats, el video feia més gran la card de debats on hi havien tots els debats. per tant, el problema era que tenies cards més altes que altres. ara ja no passa pel que veig: https://test.encomuparticipa.barcelonaencomu.cat/assemblies/plenari/f/32/debates/25

**Comment by verarojman** [comment]
@paarals merci!
